"""new2

Revision ID: 27a1857ffec2
Revises: 921142e1393c
Create Date: 2026-03-23 23:43:02.906230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a1857ffec2'
down_revision: Union[str, None] = '921142e1393c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'birthday',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'birthday',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
