"""new

Revision ID: 921142e1393c
Revises: fd99057cab11
Create Date: 2026-03-23 23:35:59.803313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921142e1393c'
down_revision: Union[str, None] = 'fd99057cab11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_info', 'about',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'about',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_info', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
