"""init

Revision ID: fd99057cab11
Revises: 
Create Date: 2026-03-04 20:55:19.153168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd99057cab11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('ban_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banned_user_id', sa.Integer(), nullable=False),
    sa.Column('ban_status', sa.Integer(), nullable=False),
    sa.Column('date_of_ban', sa.String(), nullable=False),
    sa.Column('comment_to_ban', sa.String(length=500), nullable=False),
    sa.Column('date_of_unban', sa.String(), nullable=False),
    sa.Column('comment_to_unban', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['banned_user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('till_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_user_id', sa.Integer(), nullable=False),
    sa.Column('second_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_user_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['second_user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_usernames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_usernames')
    op.drop_table('meet_info')
    op.drop_table('holidays_status')
    op.drop_table('ban_list')
    op.drop_table('user_info')
    # ### end Alembic commands ###
